name: Clojure CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.4
      with:
        cli: 1.10.1.693
          
    - name: Cache maven repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Run tests
      run: clj -M:test
