name: Clojure CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache maven repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      run: clj -M:test
