name: Clojure CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    strategy:
      matrix:
        java: ['8', '11', '15']
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java }}

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.875

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Run tests
      run: clojure -M:test
