---
name: Unit Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: '1.10.3.1053'

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          path: |
            ~/.cpcache
            ~/.m2/repository
            ~/.polylith

      - name: Create polylith config if not present
        run: mkdir -p ~/.polylith && echo "{}" > ~/.polylith/config.edn

      - name: Print Workspace Info
        run: clojure -M:poly info

      - name: Check Workspace
        run: clojure -M:poly check

      - name: Test Workspace
        run: clojure -M:poly test :all
