---
name: Unit Tests

on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '16', '17', '18']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: '1.11.1.1165'

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          path: |
            ~/.cpcache
            ~/.m2/repository
            ~/.polylith

      - name: Create polylith config if not present
        run: mkdir -p ~/.polylith && echo "{}" > ~/.polylith/config.edn

      - name: Check Workspace
        run: clojure -M:poly check

      - name: Test Workspace
        run: clojure -M:poly test :all
