---
name: Unit Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "16"]
        work-dir:
          - bases/cli-app
          - bases/cli-app/modules/cmr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1053

      - name: Run Unit Tests
        run: clojure -M:test --profile :ci
        working-directory: ${{ matrix.work-dir }}

      - name: Upload coverage
        if: ${{ matrix.java == '16' }}
        uses: codecov/codecov-action@v2.1.0
